Dev
eastgenomics/eggd_generate_STAR_genome_indices pull request #1
Opened 2022-09-23 16:01 UTC by kjwinfield

### Summary
This app uses a .gtf file of transcripts and the Sentieon STAR tool to generate genome indices, which will annotate a b38 reference genome.

What inputs are required for this app to run?
* `--sentieon_tar`: (file) Tarballed Sentieon package.
Currently defaults to use Sentieon 202112.05
* `--reference_genome`:(file) Tarballed GRCh38 reference genome FASTA + index.
Current defaults to use GRCh38.no_alt_analysis_set_chr_mask21.fasta-index.tar.gz in 001_Reference
* `--gtf_file`: (file) File providing gene transcript information.
Currently defaults to the GENCODE gtf v41 (gencode.v41.annotation.gtf.gz)

The output is a tarred and gzipped file of genome indices for the reference genome

Example DNAnexus job: [Job ID: job-GGfvVjQ42QQVZkGp50GY17kv](https://platform.dnanexus.com/projects/GFfV0qQ42QQVf6VX12zxxvx3/monitor/job/GGfvVjQ42QQVZkGp50GY17kv)
![Screenshot from 2022-09-23 16-53-21](https://user-images.githubusercontent.com/71272357/192003269-d5539ace-e76e-4063-bdd8-1e0bb5e2dc29.png)

2022-10-10 12:06 UTC, mattgarner requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1)* status: all files reviewed, 10 unresolved discussions (waiting on @kjwinfield)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0j0R8E2IQF4A82u5G:-NE0j0R8E2IQF4A82u5H:bf8jdoa) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L2)):*
> ```JSON
> {
>     "name": "make_genome_indices",
> ```

Can this be more specific?

You can also make genome indices with other tools (samtools, smalt etc) but this does not contain that functionality



_Code quote:_
```JSON
make_genome_indices
```
___
*[`dxapp.json` line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0jD8c1zOI2EY_2sPs:-NE0jD8d94KJnr6JYv3l:bg5slxm) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L4)):*
> ```JSON
>     "name": "make_genome_indices",
>     "title": "make_genome_indices",
>     "summary": "Make indices",
> ```

More descriptive please.



_Code quote:_
```JSON
Make indices
```
___
*[`dxapp.json` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0jagUCB4HwI6M2oAL:-NE0jagUCB4HwI6M2oAM:bjurqe1) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L21)):*
> ```JSON
>         },
>         {
>         "name": "reference_genome",
> ```

Perhaps `reference_genome_fasta' to make it clearer what's required.

To be fair this info is included in the associated help text, but we can make the input name more descriptive too



_Code quote:_
```JSON
reference_genome
```
___
*[`dxapp.json` line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0k5iv0VYswE414L6n:-NE0k5iv0VYswE414L6o:bffhjq7) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L30)):*
> ```JSON
>         },
>         {
>         "name": "gtf_file",
> ```

Could this be more descriptive?



_Code quote:_
```JSON
gtf_file
```
___
*[`dxapp.json` line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0kBRN2zCKTckxEik7:-NE0kBRN2zCKTckxEik8:bbm801y) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L41)):*
> ```JSON
>     "outputSpec": [
>       {
>         "name": "output_indices",
> ```

indices for what?



_Code quote:_
```JSON
output_indices
```
___
*[`dxapp.json` line 59 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0kcET7jCb_w9GgYXs:-NE0kcET7jCb_w9GgYXt:b54jxfs) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L59)):*
> ```JSON
>       "timeoutPolicy": {
>         "*": {
>           "hours": 1
> ```

Consider increasing. I see your current jobs take ~25 mins. If more fastqs were passed to the app then it may run longer and time out.

Perhaps 3h?



_Code quote:_
```JSON
 1
```
___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0kvJ46sJh-Ru1Zxvw:-NE0kvJ46sJh-Ru1Zxvx:b-u3o5vo) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/README.md#L8)):*
> ```Markdown
> ## What inputs are required for this app to run?
> * `--sentieon_tar`: (file) Tarballed Sentieon package. Currently defaults to use Sentieon 202112.05
> * `--reference_genome`:(file) Tarballed GRCh38 reference genome FASTA + index. Current defaults to use GRCh38.no_alt_analysis_set_chr_mask21.fasta-index.tar.gz in 001_Reference
> ```

Will need to be updated if input names are updated



_Code quote:_
```Markdown
reference_genome
```
___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0l4U_1vwP8INAuDSX:-NE0l4U_1vwP8INAuDSY:b-w2cyy7) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/README.md#L12)):*
> ```Markdown
> 
> ## How does this app work?
> eggd_make_genome_indices takes an input .gtf file of transcript data, and a reference genome. It creates genome indices.
> ```

...for use with STAR Fusion



_Code quote:_
```Markdown
It creates genome indices
```
___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0lBWX1KCJ72C1-a_T:-NE0lBWX1KCJ72C1-a_U:bxccyj3) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/README.md#L18)):*
> ```Markdown
> 
> ## Notes
> * This app is not ready for production use
> ```

Should we remove this?



_Code quote:_
```Markdown
This app is not ready for production use
```
___
*[`src/script.sh` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0m4j69LC1I8JJnqxQ:-NE0m4j69LC1I8JJnqxR:b-aipu7n) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/src/script.sh#L35)):*
> ```Shell
> export REFERENCE=/home/dnanexus/reference_genome/*.fa  # Reference genome, standard GRCh38
> GTF=/home/dnanexus/in/gtf_file/*gtf  # Input .gtf annotation file
> READ_LENGTH_MINUS_1=99
> ```

Have you considered making this an input with a default of 99, to make it more flexible?

If the index is specific to the read length of the data it will be used with
a) will we need to generate additional genome indexes for processing data with different read lengths?
b) does read length need to be in the filename so that it's clear which is which?



_Code quote:_
```Shell
99
```


<!-- Sent from Reviewable.io -->

2022-10-11 12:57 UTC, mattgarner requested changes
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @kjwinfield)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0j0R8E2IQF4A82u5G:-NE630UL0KTUzVa-bRWw:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L2)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Can this be more specific?

You can also make genome indices with other tools (samtools, smalt etc) but this does not contain that functionality
</blockquote></details>

Done
___
*[`dxapp.json` line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0jD8c1zOI2EY_2sPs:-NE632-29r5l0ZqxFKwP:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

More descriptive please.
</blockquote></details>

Done
___
*[`dxapp.json` line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0kBRN2zCKTckxEik7:-NE657JJ5uMtRL7B_zMM:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L41)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

indices for what?
</blockquote></details>

Done
___
*[`dxapp.json` line 59 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0kcET7jCb_w9GgYXs:-NE659jiDOiyeT1OU2dy:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L59)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Consider increasing. I see your current jobs take ~25 mins. If more fastqs were passed to the app then it may run longer and time out.

Perhaps 3h?
</blockquote></details>

Done
___
*[`dxapp.json` line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE639ln1fadPI2fEvAe:-NE639ln1fadPI2fEvAf:b-u95gpy) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/dxapp.json#L4)):*
> ```JSON
>     "name": "eggd_generate_STAR_genome_indices",
>     "title": "eggd_generate_STAR_genome_indices",
>     "summary": "This app uses Sentieon's STAR to make genome indices from an input GTF file",
> ```

and reference genome



_Code quote:_
```JSON
 from an input GTF file
```
___
*[`dxapp.json` line 25 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE63tqT0bRZuNS-Ofqp:-NE63tqT0bRZuNS-Ofqq:b-oebzx0) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/dxapp.json#L25)):*
> ```JSON
>         "help": "Tarballed GRCh38 reference genome FASTA + index",
>         "class": "file",
>         "patterns": ["*.tar.gz"],
> ```

We could be more specific with
`*.fasta-index.tar.gz`



_Code quote:_
```JSON
*.tar.gz
```
___
*[`dxapp.json` line 32 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE64Fm4EqElVildWxcw:-NE64Fm4EqElVildWxcx:b-hxszfj) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/dxapp.json#L32)):*
> ```JSON
>         "name": "annotated_transcripts_gtf",
>         "label": "annotated_transcripts_gtf",
>         "help": "Gzipped gene annotation on reference chromosomes and scaffolds in GTF format",
> ```

Perhaps note that this must match the genome build used in `reference_genome_fasta_and_index`



_Code quote:_
```JSON
Gzipped gene annotation on reference chromosomes and scaffolds in GTF format
```
___
*[`dxapp.json` line 41 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE64c3d64bgcRRqrWeF:-NE64c3d64bgcRRqrWeG:b-khlho4) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/dxapp.json#L41)):*
> ```JSON
>         "name": "read_length_minus_one",
>         "label": "read_length_minus_one",
>         "help": "Read length of data with which the genome indices will be used. Standard for Illumina instruments is 100; so the default for read length minus one is 99",
> ```

Read length, or read length -1?

This would be more user friendly if the user passed the read length, rather than the read length -1. The -1 can then be calculated within the app.



_Code quote:_
```JSON
Read length of data with which the genome indices will be used
```
___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0kvJ46sJh-Ru1Zxvw:-NE65EEU4kvg30O5FZb-:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/README.md#L8)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Will need to be updated if input names are updated
</blockquote></details>

Done
___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0l4U_1vwP8INAuDSX:-NE65HSK6z1zKhorKD8f:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/README.md#L12)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

...for use with STAR Fusion
</blockquote></details>

Done
___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0lBWX1KCJ72C1-a_T:-NE65NZ68Q53wmfQPoI5:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/README.md#L18)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should we remove this?
</blockquote></details>

Done
___
*[`src/script.sh` line 8 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE66WX81i7N5K_ZlBrj:-NE66WX81i7N5K_ZlBrk:bron31t) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/src/script.sh#L8)):*
> ```Shell
> 
> mkdir /home/dnanexus/genomeDir
> mkdir /home/dnanexus/reference_genome_fasta_and_index
> ```

Is this necessary? Won't it be created by dx-download-all-inputs?



_Code quote:_
```Shell
mkdir /home/dnanexus/reference_genome_fasta_and_index
```
___
*[`src/script.sh` line 9 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE66bzW4OFAVp8IOggM:-NE66bzW4OFAVp8IOggN:b-5hifjd) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/src/script.sh#L9)):*
> ```Shell
> mkdir /home/dnanexus/genomeDir
> mkdir /home/dnanexus/reference_genome_fasta_and_index
> mkdir /home/dnanexus/gtf
> ```

Redundant?



_Code quote:_
```Shell
/home/dnanexus/gtf
```


<!-- Sent from Reviewable.io -->

2022-10-11 13:01 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0j0R8E2IQF4A82u5G:-NE11qoE06M5uqKvQfxD:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L2)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Can this be more specific?

You can also make genome indices with other tools (samtools, smalt etc) but this does not contain that functionality
</blockquote></details>

Done.
___
*[`dxapp.json` line 4 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0jD8c1zOI2EY_2sPs:-NE11v5q9ujxav1Pd9xt:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

More descriptive please.
</blockquote></details>

Done.
___
*[`dxapp.json` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0jagUCB4HwI6M2oAL:-NE12TdGDy4_Tl0Ub_ot:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L21)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps `reference_genome_fasta' to make it clearer what's required.

To be fair this info is included in the associated help text, but we can make the input name more descriptive too
</blockquote></details>

Done.
___
*[`dxapp.json` line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0k5iv0VYswE414L6n:-NE5rzNq9ASVKR-KFqfT:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L30)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could this be more descriptive?
</blockquote></details>

Done.
___
*[`dxapp.json` line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0kBRN2zCKTckxEik7:-NE5bF0qE_94glfUb1fu:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L41)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

indices for what?
</blockquote></details>

Done.
___
*[`dxapp.json` line 59 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0kcET7jCb_w9GgYXs:-NE13hgLAc_rumbZzleg:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/dxapp.json#L59)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Consider increasing. I see your current jobs take ~25 mins. If more fastqs were passed to the app then it may run longer and time out.

Perhaps 3h?
</blockquote></details>

Done.
___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0kvJ46sJh-Ru1Zxvw:-NE5s27p5F0rTW6w-Epx:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/README.md#L8)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Will need to be updated if input names are updated
</blockquote></details>

Done.
___
*[`README.md` line 12 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0l4U_1vwP8INAuDSX:-NE14VZ81VbIbqaKY1mx:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/README.md#L12)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

...for use with STAR Fusion
</blockquote></details>

Done.
___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0lBWX1KCJ72C1-a_T:-NE14WIt8bYymxnA4HQs:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/README.md#L18)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should we remove this?
</blockquote></details>

Done.
___
*[`src/script.sh` line 35 at r1](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE0m4j69LC1I8JJnqxQ:-NE5sFsr9OpxjKCVxuW4:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/28ba089f78e994202a8ad42c66b44c113d819a3d/src/script.sh#L35)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Have you considered making this an input with a default of 99, to make it more flexible?

If the index is specific to the read length of the data it will be used with
a) will we need to generate additional genome indexes for processing data with different read lengths?
b) does read length need to be in the filename so that it's clear which is which?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-11 13:13 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE639ln1fadPI2fEvAe:-NE6ASc43gMX2TlpEOBX:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/dxapp.json#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

and reference genome
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-11 13:15 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 25 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE63tqT0bRZuNS-Ofqp:-NE6AuOZAUYCGYa9F7v7:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/dxapp.json#L25)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

We could be more specific with
`*.fasta-index.tar.gz`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-11 13:18 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 32 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE64Fm4EqElVildWxcw:-NE6BYPt8fTawCounW5T:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/dxapp.json#L32)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps note that this must match the genome build used in `reference_genome_fasta_and_index`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-11 13:24 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 41 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE64c3d64bgcRRqrWeF:-NE6Csjj3mfJpQVFMz6i:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/dxapp.json#L41)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Read length, or read length -1?

This would be more user friendly if the user passed the read length, rather than the read length -1. The -1 can then be calculated within the app.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-11 13:33 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @mattgarner)

___
*[`src/script.sh` line 8 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE66WX81i7N5K_ZlBrj:-NE6DecM8bGr72e8P2nm:bjiqlt2) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/src/script.sh#L8)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is this necessary? Won't it be created by dx-download-all-inputs?
</blockquote></details>

I think this needs to be made first as it the destination for when I unpack the tar:
if i remove it will it untar the folder directly into /home/dnanexus/in/reference_genome_fasta_and_index?



_Code snippet:_
```Shell
tar xvzf /home/dnanexus/in/reference_genome_fasta_and_index/*tar.gz -C /home/dnanexus/reference_genome_fasta_and_index
```
___
*[`src/script.sh` line 9 at r3](https://reviewable.io/reviews/eastgenomics/eggd_make_genome_indices/1#-NE66bzW4OFAVp8IOggM:-NE6ExtU51ZhdmmV2f23:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_make_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/src/script.sh#L9)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Redundant?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-12 10:56 UTC, mattgarner requested changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1)* status: all files reviewed, 8 unresolved discussions (waiting on @kjwinfield)

___
*[`dxapp.json` line 44 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAk53pBAuPLRXMRf8J:-NEAk53pBAuPLRXMRf8K:bca1iu4) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/dxapp.json#L44)):*
> ```JSON
>         "class": "int",
>         "patterns": ["*"],
>         "default": 99, 
> ```

Default is set at 99, but help text says it's 100



_Code quote:_
```JSON
        "help": "Read length of data with which the genome indices will be used. Standard for Illumina instruments is 100; so the default is 100",
        "class": "int",
        "patterns": ["*"],
        "default": 99,
```
___
*[`src/script.sh` line 8 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NE66WX81i7N5K_ZlBrj:-NEAkYGg9iDHpTDkVQ9N:b5h2puq) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/a4d718fa7aec05aceb7548442bd43ac29ffdd610/src/script.sh#L8)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

I think this needs to be made first as it the destination for when I unpack the tar:
if i remove it will it untar the folder directly into /home/dnanexus/in/reference_genome_fasta_and_index?
</blockquote></details>

You're correct, I didn't notice that the /in/ part was missing from the path
___
*[`src/script.sh` line 25 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAlAZO3St4JjqOvB3b:-NEAlAZP4GXDEGzn77N_:b-1ccm3o) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L25)):*
> ```Shell
> # NUMBER_THREADS input to STAR needs the number of cores on the server node
> # This can be extracted from the DNAnexus instance type
> INSTANCE=$(dx describe --json $DX_JOB_ID | jq -r '.instanceType')  # Extract instance type
> ```

Should only use caps for ENV variables.

Could this be `instance` instead?

Same applies to other var names below



_Code quote:_
```Shell
INSTANCE
```
___
*[`src/script.sh` line 46 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAmdkY0K82JEvxjsxd:-NEAmdkY0K82JEvxjsxe:b1sj562) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L46)):*
> ```Shell
> CUT_REFERENCE=${CUT_REFERENCE%.fasta-index.tar.gz*}
> CUT_GTF=${GTFNAME##*/}
> CUT_GTF=${CUT_GTF%.gtf*}
> ```

Could you add an explanatory comment for this part?



_Code quote:_
```Shell
CUT_REFERENCE=${REFNAME##*/}
CUT_REFERENCE=${CUT_REFERENCE%.fasta-index.tar.gz*}
CUT_GTF=${GTFNAME##*/}
CUT_GTF=${CUT_GTF%.gtf*}
```
___
*[`src/script.sh` line 49 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAmzHREIe1JUqXMhHR:-NEAmzHREIe1JUqXMhHS:b-7w8f6j) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L49)):*
> ```Shell
> FILENAME=ref_${CUT_REFERENCE}-gtf_${CUT_GTF}-readlength${read_length}
> 
> # Configure output directories with output filename 
> ```

Configure or Create?



_Code quote:_
```Shell
Configure
```
___
*[`src/script.sh` line 50 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEApSVBEefqQ42LHVNJ:-NEApSVCAxRmlA98puKZ:b5xfqas) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L50)):*
> ```Shell
> 
> # Configure output directories with output filename 
> mkdir /home/dnanexus/$FILENAME
> ```

Further down (line 57) we set `OUTPUT_DIR=/home/dnanexus/$FILENAME`
Could this line be moved under the `FILENAME=...` line above, then you can use `OUTPUT_DIR` as the input to `mkdir`

i.e.
FILENAME=...
OUTPUT_DIR=...
mkdir OUTPUT_DIR

This would remove some repetition, as we use the same variable to create the path and to refer to it later



_Code quote:_
```Shell
mkdir /home/dnanexus/$FILENAME
```
___
*[`src/script.sh` line 55 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAn7Dd2fQlVp-nTuMr:-NEAn7Dd2fQlVp-nTuMs:b40zm4d) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L55)):*
> ```Shell
> # Define input variables for STAR command
> NUMBER_THREADS=${INSTANCE##*_x}
> export REFERENCE=/home/dnanexus/reference_genome_fasta_and_index/*.fa  # Reference genome, standard GRCh38
> ```

Does it have to be 38?



_Code quote:_
```Shell
standard GRCh38
```
___
*[`src/script.sh` line 71 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAnynq0O7Vk7XBFSak:-NEAnynq0O7Vk7XBFSal:btnej8l) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L71)):*
> ```Shell
> tar -czvf $FILENAME.tar.gz /home/dnanexus/$FILENAME
> # Move to /out/ folder to allow output to be uploaded
> #mv $FILENAME.tar.gz /home/dnanexus/out/$FILENAME
> ```

Please remove if no longer needed



_Code quote:_
```Shell
# Move to /out/ folder to allow output to be uploaded
#mv $FILENAME.tar.gz /home/dnanexus/out/$FILENAME
```


<!-- Sent from Reviewable.io -->

2022-10-13 14:12 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1)* status: 3 of 7 files reviewed, 8 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 44 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAk53pBAuPLRXMRf8J:-NEBTwQjC9tnePnHfqdm:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/dxapp.json#L44)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Default is set at 99, but help text says it's 100
</blockquote></details>

Done.
___
*[`src/script.sh` line 25 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAlAZO3St4JjqOvB3b:-NEBxsagBBnd14Tdxoby:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L25)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should only use caps for ENV variables.

Could this be `instance` instead?

Same applies to other var names below
</blockquote></details>

Done.
___
*[`src/script.sh` line 46 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAmdkY0K82JEvxjsxd:-NEBxtqSD7N611t_v6a6:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L46)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could you add an explanatory comment for this part?
</blockquote></details>

Done.
___
*[`src/script.sh` line 49 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAmzHREIe1JUqXMhHR:-NEBxuz6E87yJ2aqkS-Y:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L49)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Configure or Create?
</blockquote></details>

Done.
___
*[`src/script.sh` line 50 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEApSVBEefqQ42LHVNJ:-NEBxwng1XBRv70YemHJ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L50)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Further down (line 57) we set `OUTPUT_DIR=/home/dnanexus/$FILENAME`
Could this line be moved under the `FILENAME=...` line above, then you can use `OUTPUT_DIR` as the input to `mkdir`

i.e.
FILENAME=...
OUTPUT_DIR=...
mkdir OUTPUT_DIR

This would remove some repetition, as we use the same variable to create the path and to refer to it later
</blockquote></details>

Done.
___
*[`src/script.sh` line 55 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAn7Dd2fQlVp-nTuMr:-NEGfqth3RhavABDLVd0:b-ewvygj) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L55)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does it have to be 38?
</blockquote></details>

STAR works with either, so I've edited out explicit references to build and just stated that the build for the reference genome and the gtf must be the same
___
*[`src/script.sh` line 71 at r8](https://reviewable.io/reviews/eastgenomics/eggd_generate_star_genome_indices/1#-NEAnynq0O7Vk7XBFSak:-NEBy1JG0kTWgZOdVapU:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_star_genome_indices/blob/731c145cc5edc39bb5975a24b1c0ab61e328720a/src/script.sh#L71)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Please remove if no longer needed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-19 12:47 UTC, closed without merging